linters-settings:
  dupl:
    threshold: 125
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - experimental
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 31
  gofumpt:
    extra-rules: true
  govet:
    enable:
      - shadow
  lll:
    line-length: 140
  misspell:
    locale: US
  revive:
    confidence: 0

linters:
  enable-all: true
  disable-all: false
  # Linters we don't like
  # Comments help explain why its disabled or point at ones we should not disable but will take a little work
  # If its not commented its likely because its just too annoying or we don't find useful
  disable:
    # following block should all definitely be enabled, they have good/valid claims
    # I just don't want to do it in this PR :/
    - err113
    - gosec
    - gocritic
    - revive
    - stylecheck
    - vet

    - cyclop
    - depguard
    - dupl
    - errname # maybe should be enabled
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - godot
    - godox
    - inamedparam
    - interfacebloat
    - ireturn # should be enabled, ironlib needs some changes
    - lll # not previously enabled, ironlib and mctl both fail this
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns # should be enabled, probably
    - paralleltest
    - perfsprint
    - tagliatelle
    - tenv # should be enabled
    - testpackage
    - testifylint # should be enabled
    - thelper # should be enabled
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1016"
